// @date 02 May 2019
// @author Anton Kozlovskyi

export const ADD_TO_REQUEST_QUEUE = 'ADD_TO_REQUEST_QUEUE';
export const REMOVE_FROM_REQUEST_QUEUE_SUCCESS = 'REMOVE_FROM_REQUEST_QUEUE_SUCCESS';
export const REMOVE_FROM_REQUEST_QUEUE_FAIL = 'REMOVE_FROM_REQUEST_QUEUE_FAIL';

const AVAILABLE_REQUEST_QUEUE_ACTIONS = (action) => {
    if (![ADD_TO_REQUEST_QUEUE, REMOVE_FROM_REQUEST_QUEUE_FAIL, REMOVE_FROM_REQUEST_QUEUE_SUCCESS].includes(action)){
        throw new Error("check AVAILABLE_REQUEST_QUEUE_ACTIONS");
    }
};

// const 